-- urth. — rebuild Loose Flower & Foliage catalogue  (2026-07-20)
-- Per-stem for most; selected flowers also have Half bunch / Full bunch options (unit = stem count).
-- Only touches type Loose Flower/Foliage. App also has this built in (LOOSE_SEED); running is optional.
begin;
delete from products where type in ('Loose Flower', 'Foliage');
insert into products (name, type, price_inr, flowers) values
  ('Agapanthus', 'Loose Flower', 200, 'Per stem'),
  ('Alstroemeria', 'Loose Flower', 35, 'Per stem'),
  ('Alstroemeria (Half bunch)', 'Loose Flower', 175, '5 stems'),
  ('Alstroemeria (Full bunch)', 'Loose Flower', 350, '10 stems'),
  ('Amaranth', 'Loose Flower', 100, 'Per stem'),
  ('Amaranth (Bunch)', 'Loose Flower', 500, '5 stems'),
  ('Anthurium', 'Loose Flower', 20, 'Per stem'),
  ('Anthurium (Bunch)', 'Loose Flower', 100, '5 stems'),
  ('Asiatic Lily', 'Loose Flower', 80, 'Per stem'),
  ('Asiatic Lily (Half bunch)', 'Loose Flower', 400, '5 stems'),
  ('Asiatic Lily (Full bunch)', 'Loose Flower', 800, '10 stems'),
  ('Bird of Paradise', 'Loose Flower', 80, 'Per stem'),
  ('Bird of Paradise (Bunch)', 'Loose Flower', 400, '5 stems'),
  ('Calla Lily', 'Loose Flower', 100, 'Per stem'),
  ('Calla Lily (Bunch)', 'Loose Flower', 500, '5 stems'),
  ('Carnation', 'Loose Flower', 40, 'Per stem'),
  ('Carnation (Half bunch)', 'Loose Flower', 200, '5 stems'),
  ('Carnation (Full bunch)', 'Loose Flower', 400, '10 stems'),
  ('Chrysanthemum', 'Loose Flower', 800, 'Per bunch'),
  ('Chrysanthemum (Half bunch)', 'Loose Flower', 400, 'Per half bunch'),
  ('Eryngium', 'Loose Flower', 120, 'Per stem'),
  ('Eryngium (Half bunch)', 'Loose Flower', 600, '5 stems'),
  ('Eryngium (Full bunch)', 'Loose Flower', 1200, '10 stems'),
  ('Eustoma', 'Loose Flower', 80, 'Per stem'),
  ('Eustoma (Half bunch)', 'Loose Flower', 400, '5 stems'),
  ('Eustoma (Full bunch)', 'Loose Flower', 800, '10 stems'),
  ('Gerbera', 'Loose Flower', 25, 'Per stem'),
  ('Gerbera (Bunch)', 'Loose Flower', 250, '10 stems'),
  ('Gladiolus', 'Loose Flower', 100, 'Per stem'),
  ('Gladiolus (Half bunch)', 'Loose Flower', 500, '5 stems'),
  ('Gladiolus (Full bunch)', 'Loose Flower', 1000, '10 stems'),
  ('Gypsophila', 'Loose Flower', 800, 'Per bunch'),
  ('Gypsophila (Half bunch)', 'Loose Flower', 400, 'Per half bunch'),
  ('Hydrangea', 'Loose Flower', 500, 'Per stem'),
  ('Liatris', 'Loose Flower', 80, 'Per stem'),
  ('Liatris (Bunch)', 'Loose Flower', 400, '5 stems'),
  ('Limonium', 'Loose Flower', 450, 'Per bunch'),
  ('Limonium (Half bunch)', 'Loose Flower', 225, 'Per half bunch'),
  ('Dendobrium Orchid', 'Loose Flower', 60, 'Per stem'),
  ('Oriental Lily', 'Loose Flower', 200, 'Per stem'),
  ('Oriental Lily (Half bunch)', 'Loose Flower', 1000, '5 stems'),
  ('Oriental Lily (Full bunch)', 'Loose Flower', 2000, '10 stems'),
  ('Ornithogalum', 'Loose Flower', 30, 'Per stem'),
  ('Ornithogalum (Half bunch)', 'Loose Flower', 150, '5 stems'),
  ('Ornithogalum (Full bunch)', 'Loose Flower', 300, '10 stems'),
  ('Rose', 'Loose Flower', 50, 'Per stem'),
  ('Rose (Half bunch)', 'Loose Flower', 500, '10 stems'),
  ('Rose (Full bunch)', 'Loose Flower', 1000, '20 stems'),
  ('Areca Palm (Foliage)', 'Foliage', 120, 'Per bunch'),
  ('Spray Carnation', 'Loose Flower', 45, 'Per stem'),
  ('Spray Carnation (Half bunch)', 'Loose Flower', 225, '5 stems'),
  ('Spray Carnation (Full bunch)', 'Loose Flower', 450, '10 stems'),
  ('Statice', 'Loose Flower', 400, 'Per bunch'),
  ('Statice (Half bunch)', 'Loose Flower', 200, 'Per half bunch'),
  ('Sunflower', 'Loose Flower', 180, 'Per stem'),
  ('Sweet William', 'Loose Flower', 30, 'Per stem'),
  ('Sweet William (Half bunch)', 'Loose Flower', 150, '5 stems'),
  ('Sweet William (Full bunch)', 'Loose Flower', 300, '10 stems'),
  ('Tuberose', 'Loose Flower', 60, 'Per stem'),
  ('Tuberose (Half bunch)', 'Loose Flower', 600, '10 stems'),
  ('Tuberose (Full bunch)', 'Loose Flower', 1200, '20 stems'),
  ('Ping Pong', 'Loose Flower', 100, 'Per stem'),
  ('Ping Pong (Half bunch)', 'Loose Flower', 500, '5 stems'),
  ('Ping Pong (Full bunch)', 'Loose Flower', 1000, '10 stems'),
  ('Disbud', 'Loose Flower', 100, 'Per stem'),
  ('Disbud (Half bunch)', 'Loose Flower', 500, '5 stems'),
  ('Disbud (Full bunch)', 'Loose Flower', 1000, '10 stems'),
  ('Roquette Celosia', 'Loose Flower', 40, 'Per stem'),
  ('Roquette Celosia (Half bunch)', 'Loose Flower', 200, '5 stems'),
  ('Roquette Celosia (Full bunch)', 'Loose Flower', 400, '10 stems'),
  ('Snapdragon', 'Loose Flower', 60, 'Per stem'),
  ('Snapdragon (Half bunch)', 'Loose Flower', 300, '5 stems'),
  ('Snapdragon (Full bunch)', 'Loose Flower', 600, '10 stems'),
  ('Allium', 'Loose Flower', 80, 'Per stem'),
  ('Allium (Bunch)', 'Loose Flower', 400, '5 stems'),
  ('Balloon Flower', 'Loose Flower', 120, 'Per stem'),
  ('Balloon Flower (Bunch)', 'Loose Flower', 600, '5 stems'),
  ('Crocosmia', 'Loose Flower', 50, 'Per stem'),
  ('Crocosmia (Half bunch)', 'Loose Flower', 250, '5 stems'),
  ('Crocosmia (Full bunch)', 'Loose Flower', 500, '10 stems'),
  ('Heliconia - Hanging', 'Loose Flower', 250, 'Per stem'),
  ('Ornamental Pineapple', 'Loose Flower', 100, 'Per stem'),
  ('Helicona - Iris (Standing)', 'Loose Flower', 250, 'Per stem'),
  ('Torch Ginger', 'Loose Flower', 150, 'Per stem'),
  ('Havana Cigar', 'Loose Flower', 200, 'Per stem'),
  ('Orchids - Mokara', 'Loose Flower', 100, 'Per stem'),
  ('Orchid - Bright Red', 'Loose Flower', 150, 'Per stem'),
  ('Orchid - James Story Yellow', 'Loose Flower', 200, 'Per stem'),
  ('Heliconia - Caribaea (Standing)', 'Loose Flower', 250, 'Per stem'),
  ('Heliconia - Mexican Gold (Standing)', 'Loose Flower', 250, 'Per stem'),
  ('Heliconia - Sexy Pink (Hanging)', 'Loose Flower', 250, 'Per stem'),
  ('Heliconia - Temptress (Hanging)', 'Loose Flower', 250, 'Per stem'),
  ('Orchid - Anne Black', 'Loose Flower', 100, 'Per stem'),
  ('Amaryllis', 'Loose Flower', 100, 'Per stem'),
  ('Amaryllis (Bunch)', 'Loose Flower', 500, '5 stems'),
  ('Silver Brunia', 'Loose Flower', 800, 'Per stem'),
  ('Red Hot Poker', 'Loose Flower', 100, 'Per stem'),
  ('Helichrysum', 'Loose Flower', 70, 'Per stem'),
  ('Helichrysum (Half bunch)', 'Loose Flower', 350, '5 stems'),
  ('Helichrysum (Full bunch)', 'Loose Flower', 700, '10 stems'),
  ('Costus Stenophyllus', 'Loose Flower', 150, 'Per stem'),
  ('Orchid - Vandachnis', 'Loose Flower', 250, 'Per stem'),
  ('Orchid - Aranda', 'Loose Flower', 150, 'Per stem'),
  ('Orchid - Arachnis', 'Loose Flower', 150, 'Per stem'),
  ('Veronica', 'Loose Flower', 60, 'Per stem'),
  ('Veronica (Half bunch)', 'Loose Flower', 300, '5 stems'),
  ('Veronica (Full bunch)', 'Loose Flower', 600, '10 stems'),
  ('Craspedia', 'Loose Flower', 70, 'Per stem'),
  ('Craspedia (Bunch)', 'Loose Flower', 350, '5 stems'),
  ('Celosia', 'Loose Flower', 60, 'Per stem'),
  ('Celosia (Bunch)', 'Loose Flower', 600, '10 stems'),
  ('Stock Flower', 'Loose Flower', 80, 'Per stem'),
  ('Stock Flower (Half bunch)', 'Loose Flower', 400, '5 stems'),
  ('Stock Flower (Full bunch)', 'Loose Flower', 800, '10 stems'),
  ('Foxglove', 'Loose Flower', 60, 'Per stem'),
  ('Foxglove (Half bunch)', 'Loose Flower', 300, '5 stems'),
  ('Foxglove (Full bunch)', 'Loose Flower', 600, '10 stems'),
  ('Rattle', 'Loose Flower', 150, 'Per stem'),
  ('Delphinium', 'Loose Flower', 200, 'Per stem'),
  ('Silver Tip', 'Loose Flower', 20, 'Per stem'),
  ('Silver Tip (Half bunch)', 'Loose Flower', 100, '5 stems'),
  ('Silver Tip (Full bunch)', 'Loose Flower', 200, '10 stems'),
  ('Hypericum Berries', 'Loose Flower', 400, 'Per stem'),
  ('Spray Rose', 'Loose Flower', 100, 'Per stem'),
  ('Spray Rose (Half bunch)', 'Loose Flower', 500, '5 stems'),
  ('Spray Rose (Full bunch)', 'Loose Flower', 1000, '10 stems'),
  ('Ornamental Grass', 'Loose Flower', 40, 'Per stem'),
  ('Ornamental Grass (Half bunch)', 'Loose Flower', 200, '5 stems'),
  ('Ornamental Grass (Full bunch)', 'Loose Flower', 400, '10 stems'),
  ('Bulrush', 'Loose Flower', 160, 'Per stem'),
  ('Bulrush (Half bunch)', 'Loose Flower', 800, '5 stems'),
  ('Bulrush (Full bunch)', 'Loose Flower', 1600, '10 stems'),
  ('Bells Of Ireland', 'Loose Flower', 70, 'Per stem'),
  ('Bells Of Ireland (Half bunch)', 'Loose Flower', 350, '5 stems'),
  ('Bells Of Ireland (Full bunch)', 'Loose Flower', 700, '10 stems'),
  ('Red Button Ginger Big', 'Loose Flower', 120, 'Per stem'),
  ('Red Button Ginger Big (Half bunch)', 'Loose Flower', 600, '5 stems'),
  ('Red Button Ginger Big (Full bunch)', 'Loose Flower', 1200, '10 stems'),
  ('Curcuma', 'Loose Flower', 100, 'Per stem'),
  ('Curcuma (Half bunch)', 'Loose Flower', 500, '5 stems'),
  ('Curcuma (Full bunch)', 'Loose Flower', 1000, '10 stems'),
  ('Fennel Flower', 'Loose Flower', 40, 'Per stem'),
  ('Fennel Flower (Half bunch)', 'Loose Flower', 200, '5 stems'),
  ('Fennel Flower (Full bunch)', 'Loose Flower', 400, '10 stems'),
  ('Trachelium Dianthus', 'Loose Flower', 160, 'Per stem'),
  ('Trachelium Dianthus (Half bunch)', 'Loose Flower', 800, '5 stems'),
  ('Trachelium Dianthus (Full bunch)', 'Loose Flower', 1600, '10 stems'),
  ('Silky Asparagus Fern (Foliage)', 'Foliage', 250, 'Per bunch'),
  ('Cypress (Foliage)', 'Foliage', 150, 'Per bunch'),
  ('Eucalyptus (Foliage)', 'Foliage', 600, 'Per bunch'),
  ('Eucalyptus (Foliage) (Half bunch)', 'Foliage', 300, 'Half bunch'),
  ('Fish Tail Palm (Foliage)', 'Foliage', 150, 'Per bunch'),
  ('Ivy Leaves (Foliage)', 'Foliage', 150, 'Per bunch'),
  ('Ping Pong (Foliage)', 'Foliage', 200, 'Per bunch'),
  ('Pin Cushion', 'Loose Flower', 500, 'Per stem'),
  ('Brassica (Foliage)', 'Foliage', 150, 'Per bunch'),
  ('Goldenrod (Foliage)', 'Foliage', 200, 'Per bunch'),
  ('Kamini (Foliage)', 'Foliage', 200, 'Per bunch'),
  ('Podocarpus (Foliage)', 'Foliage', 150, 'Per bunch'),
  ('Leather Fern (Foliage)', 'Foliage', 150, 'Per bunch'),
  ('Dracaena (Foliage)', 'Foliage', 100, 'Per bunch'),
  ('BOP Leafs (Foliage)', 'Foliage', 150, 'Per bunch'),
  ('Raphis Palm (Foliage)', 'Foliage', 250, 'Per bunch'),
  ('Monstera (Foliage)', 'Foliage', 300, 'Per bunch'),
  ('Bottle Brush (Foliage)', 'Foliage', 300, 'Per bunch'),
  ('Purple Majesty', 'Loose Flower', 130, 'Per stem'),
  ('Purple Majesty (Half bunch)', 'Loose Flower', 650, '5 stems'),
  ('Purple Majesty (Full bunch)', 'Loose Flower', 1300, '10 stems'),
  ('Song of India (Foliage)', 'Foliage', 120, 'Per bunch'),
  ('Ornamental Ginger', 'Loose Flower', 200, 'Per stem'),
  ('Calathea Vittatta (Foliage)', 'Foliage', 50, 'Per stem'),
  ('Fishtail Palm Rope', 'Loose Flower', 100, 'Per stem'),
  ('Aster', 'Loose Flower', 70, 'Per stem'),
  ('Aster (Half bunch)', 'Loose Flower', 350, '5 stems'),
  ('Aster (Full bunch)', 'Loose Flower', 700, '10 stems'),
  ('Campanula', 'Loose Flower', 75, 'Per stem'),
  ('Campanula (Half bunch)', 'Loose Flower', 375, '5 stems'),
  ('Campanula (Full bunch)', 'Loose Flower', 750, '10 stems'),
  ('Clarkia', 'Loose Flower', 45, 'Per stem'),
  ('Clarkia (Half bunch)', 'Loose Flower', 225, '5 stems'),
  ('Clarkia (Full bunch)', 'Loose Flower', 450, '10 stems'),
  ('Cymbedium', 'Loose Flower', 1000, 'Per stem'),
  ('Tulips', 'Loose Flower', 250, 'Per stem'),
  ('Tulips (Half bunch)', 'Loose Flower', 1250, '5 stems'),
  ('Tulips (Full bunch)', 'Loose Flower', 2500, '10 stems'),
  ('Torch lily', 'Loose Flower', 200, 'Per stem'),
  ('King Protea', 'Loose Flower', 2500, 'Per stem'),
  ('Regular Asparagus Fern', 'Loose Flower', 200, 'Per bunch'),
  ('Red Button Ginger Small', 'Loose Flower', 65, 'Per stem'),
  ('Red Button Ginger Small (Half bunch)', 'Loose Flower', 325, '5 stems'),
  ('Red Button Ginger Small (Full bunch)', 'Loose Flower', 650, '10 stems'),
  ('SHampoo ginger', 'Loose Flower', 200, 'Per stem'),
  ('berry', 'Loose Flower', 200, 'Per stem'),
  ('brown calla lily', 'Loose Flower', 250, 'Per stem');
commit;
select type, count(*) as items from products where type in ('Loose Flower','Foliage') group by type
union all select 'TOTAL', count(*) from products where type in ('Loose Flower','Foliage');
