-- urth. — push notification subscriptions table (2026-07-20)
-- Stores one row per device/browser that has enabled alerts (via the Web Push
-- standard). The Edge Function (below, deployed separately) reads this table
-- to know who to notify when an order's status changes.
--
-- STEP 1 — paste this into Supabase → SQL Editor → Run.

create table if not exists push_subscriptions (
  id bigint generated by default as identity primary key,
  endpoint text not null unique,
  p256dh text not null,
  auth text not null,
  ua text,
  created_at timestamptz default now()
);

alter table push_subscriptions enable row level security;

-- Any authenticated staff member can register/see subscriptions (same trust
-- model as the rest of the app — RLS requires login, no public access).
create policy if not exists "push_subscriptions_rw" on push_subscriptions
  for all to authenticated using (true) with check (true);
