-- =============================================================================
-- urth. Order Dashboard — COMPLETE SCHEMA (rebuild from zero)
-- =============================================================================
-- Running this whole file on a brand-new, empty Supabase project recreates the
-- entire database structure. It does NOT contain data — restore that from an
-- export in backup/data/ (see backup/README.md).
--
-- Every statement is idempotent (`if not exists` / `on conflict`), so this file
-- is safe to run against an existing project too. Paste into
-- Supabase -> SQL Editor -> Run.
--
-- Generated 2026-09-10, verified against the live project by probing which
-- columns the API actually accepts. See MIGRATION-STATUS.md for what was
-- applied at that moment vs. still pending.
-- =============================================================================

-- 1. Types --------------------------------------------------------------------
do $$ begin
  create type order_status as enum
    ('new','confirmed','prep','ready','dispatched','delivered','cancelled');
exception when duplicate_object then null;
end $$;

-- 2. Core tables --------------------------------------------------------------
create table if not exists products (
  id        bigint generated always as identity primary key,
  name      text,
  type      text default 'Bouquet',
  price_inr integer default 0,
  flowers   text
);

create table if not exists subscriptions (
  id            bigint generated always as identity primary key,
  client        text,
  type          text,
  preferred_day text,
  status        text default 'On-Going',
  value_inr     integer default 0,
  flower_prefs  text,
  last_delivery date,
  end_date      date
);

create table if not exists orders (
  id             bigint generated always as identity primary key,
  order_no       text,
  customer_name  text,
  phone          text,          -- the CUSTOMER (who placed the order)
  order_date     date,
  delivery_date  date not null,
  order_type     text,
  details        text,
  value_inr      integer default 0,   -- post-discount total (auto-derived)
  delivery_time  text,
  source         text,
  transport_mode text,
  maker          text,          -- legacy summary of makers[] (comma-joined)
  payment_status text,
  address        text,
  status         order_status default 'new',
  urgent         boolean default false,
  created_at     timestamptz default now(),
  message_note   text,          -- customer's note to go with the flowers
  polaroid       boolean default false,  -- legacy summary of polaroid_qty > 0
  remarks        text,          -- internal notes, not customer-facing
  items          jsonb,         -- [{type,det,val},...]; null = legacy single-item
  discount       jsonb          -- {type:'pct'|'amt', value}; null = none
);

-- 3. Staff roster (migration 2026-08-01) --------------------------------------
alter table orders add column if not exists makers jsonb;
alter table orders add column if not exists owners jsonb;

create table if not exists staff (
  id         bigint generated always as identity primary key,
  name       text not null,
  role       text not null check (role in ('maker','owner')),
  created_at timestamptz default now(),
  unique (name, role)
);

-- 4. Polaroid quantity (migration 2026-08-12) ---------------------------------
alter table orders add column if not exists polaroid_qty integer default 0;
update orders set polaroid_qty = 1
  where polaroid is true and coalesce(polaroid_qty,0) = 0;

-- 5. Receiver phone + attachments (migration 2026-09-10) ----------------------
alter table orders add column if not exists receiver_phone text;
alter table orders add column if not exists attachments jsonb;

-- 6. Push subscriptions (migration 2026-07-20) --------------------------------
create table if not exists push_subscriptions (
  id         bigint generated by default as identity primary key,
  endpoint   text not null unique,
  p256dh     text not null,
  auth       text not null,
  ua         text,
  created_at timestamptz default now()
);

-- 7. Row Level Security -------------------------------------------------------
-- Trust model: RLS is ON everywhere and requires a logged-in user. The anon key
-- embedded in index.html can therefore read NOTHING on its own -- verified
-- 2026-09-10: anon requests return [] for every table.
alter table products           enable row level security;
alter table subscriptions      enable row level security;
alter table orders             enable row level security;
alter table staff              enable row level security;
alter table push_subscriptions enable row level security;

drop policy if exists products_rw           on products;
drop policy if exists subscriptions_rw      on subscriptions;
drop policy if exists orders_rw             on orders;
drop policy if exists staff_rw              on staff;
drop policy if exists push_subscriptions_rw on push_subscriptions;

create policy products_rw           on products           for all to authenticated using (true) with check (true);
create policy subscriptions_rw      on subscriptions      for all to authenticated using (true) with check (true);
create policy orders_rw             on orders             for all to authenticated using (true) with check (true);
create policy staff_rw              on staff              for all to authenticated using (true) with check (true);
create policy push_subscriptions_rw on push_subscriptions for all to authenticated using (true) with check (true);

-- 8. Storage: private attachments bucket --------------------------------------
-- MUST stay public = false. Flipping it public puts customer reference photos
-- on guessable, unauthenticated URLs.
insert into storage.buckets (id, name, public, file_size_limit)
values ('order-files', 'order-files', false, 20971520)
on conflict (id) do update set public = false, file_size_limit = 20971520;

drop policy if exists "order-files read"   on storage.objects;
drop policy if exists "order-files insert" on storage.objects;
drop policy if exists "order-files update" on storage.objects;
drop policy if exists "order-files delete" on storage.objects;

create policy "order-files read"   on storage.objects for select to authenticated
  using (bucket_id = 'order-files');
create policy "order-files insert" on storage.objects for insert to authenticated
  with check (bucket_id = 'order-files');
create policy "order-files update" on storage.objects for update to authenticated
  using (bucket_id = 'order-files') with check (bucket_id = 'order-files');
create policy "order-files delete" on storage.objects for delete to authenticated
  using (bucket_id = 'order-files');

-- 9. Seed the staff roster ----------------------------------------------------
insert into staff (name, role) values
  ('Surjith','maker'),('Ganesh','maker'),('Ranjith','maker'),('Dharma','maker'),
  ('Dinesh','maker'),('Rickwin','maker'),('Pradeep','maker')
on conflict (name, role) do nothing;

-- =============================================================================
-- NOT COVERED BY THIS FILE (cannot be recreated from SQL):
--   * Staff login accounts (Authentication -> Users). Recreate by hand.
--     "Confirm email" must be OFF so staff can be added without an inbox.
--   * Auth settings. Verify "Allow new users to sign up" is OFF
--     (confirmed disable_signup:true on 2026-09-10).
--   * The Edge Function notify-order-status (source is in supabase/functions/).
-- =============================================================================
